### ISSUE TITLE
Some decks are not working

### ISSUE THREAD

**Issue by punchinglikes** [Kingal1337/YugiohProxyMaker#1]
I keep getting an out of bounds error when using certain decks, I cannot figure out the cause though. One deck that does not work is 
```
#created by ygopro2
#main
7733560
102380
102380
102380
94004268
94004268
94004268
31305911
69181753
69181753
69181753
33245030
33245030
33245030
91740879
91740879
91740879
33904024
38992735
38992735
38992735
56948373
56948373
76375976
76375976
76375976
95308449
49238328
49238328
73628505
77538567
77538567
77538567
41420027
41420027
41420027
66742250
66742250
66742250
86778566
86778566
89208725
36975314
36975314
36975314
59744639
59744639
59744639
36458063
#extra
10406322
10406322
10406322
10678778
10678778
10678778
94119480
94119480
94119480
21044178
21044178
21044178
65301952
65301952
65301952
!side
89631139
```

**Comment by Kingal1337** [comment]
Which version are you using? that error occurs in version 1.0.0, but was fixed in 1.1.0

Link to 1.1.0: https://github.com/Kingal1337/YugiohProxyMaker/releases/tag/1.1.0

**Comment by punchinglikes** [comment]
Sorry for the late reply, I can confirm this is happening on 1.1.0

**Comment by Kingal1337** [comment]
what is happening in version 1.1.0? I am unable to reproduce the bug with the decklist you provided.
Is the IndexOutOfBounds error happening in 1.1.0 or is it is not happening?
And which command are you using?
If the bug is occurring, can you also send the file you are using?

**Comment by Kingal1337** [comment]
I believe I have found the bug that was causing the IndexOutOfBounds error.
The IndexOutOfBounds error occurs when there is an empty line anywhere within the file and I believe that in your .ydk file there was an empty line at the bottom of your file, but since you copy and pasted the decklist into Github, GitHub must have removed it automatically.  The fix will be coming in the next release. :)

**Comment by punchinglikes** [comment]
For some reason even without a space in my file, I still get the out of bounds error. I'm using `java -jar Yugioh-Proxy-Maker-1.1.0.jar "pathtoydk" "destination" yes yes`

**Comment by Kingal1337** [comment]
is it possible for you to send me the ydk file you use? and I also released a new version, could you try that as well?

**Comment by punchinglikes** [comment]
the ydk I used is the exact one that github is showing, I copied and pasted to see if it was a format thing github fixed but no. Let me try the new version right now.

**Comment by punchinglikes** [comment]
Update: It seems to be working now when I updated to the newest version, I will let you know if I ever come across it again.

**Comment by Kingal1337** [comment]
that is good to hear, I would check to make sure it is generating all the cards in your deck.

**Comment by punchinglikes** [comment]
I just checked and it seems to have done the job, thank you.
